<div class="row-fluid">
    <div class="span12">
        <h1><small class="text-error">New <span class="text-info"><?= $category->getName() ?></span> Item</small></h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span8 offset1">
        <?= TwbForm::horizontal($form) ?>
    </div>
</div>
<script>
    $(function () {
        $('form#<?= $form->getName() ?> [type="submit"]').parent().append('<input class="btn btn-primary" type="submit" name="saveAndNew" value="Save and Add New" />');
    });
</script>
