<div class="row-fluid">
	<div class="span12">
		<h1><small class="text-error">Item View</small></h1>
		<hr />
	</div>
</div>
<div class="row-fluid">
	<div class="span8 offset1">
		
			<p><span class="text-info">Category</span>: <span><?= $model->getCategory() ?></span></p>
			
			<p><span class="text-info">Name</span>: <span><?= $model->getName() ?></span></p>
			
			<p><span class="text-info">Short Description</span>: <span><?= $model->getShortDescription() ?></span></p>
			
			<p><span class="text-info">Long Description</span>: <span><?= $model->getLongDescription() ?></span></p>
			
			<p><span class="text-info">Images</span>: <span><?= $model->getImages() ?></span></p>
			
			<p><span class="text-info">Price</span>: <span><?= $model->getPrice() ?></span></p>
			
			<p><span class="text-info">In Stock</span>: <span><?= $model->getInStock() ?></span></p>
			
			<p><span class="text-info">Too Low Count</span>: <span><?= $model->getTooLowCount() ?></span></p>
			
			<p><span class="text-info">Too Low Message</span>: <span><?= $model->getTooLowMessage() ?></span></p>
			
			<p><span class="text-info">Shipping Information</span>: <span><?= $model->getShippingInformation() ?></span></p>
			
			<p><span class="text-info">Payment Options</span>: <span><?= $model->getPaymentOptions() ?></span></p>
			
			<p><span class="text-info">Id</span>: <span><?= $model->getId() ?></span></p>
			
	</div>
</div>
		