<div class="row-fluid">
    <div class="span12 page-header">
        <h1><small class="text-info">Welcome <?= $this->userIdentity()->getUser()->getFirstName() ?></small></h1>
    </div>
</div>
<div class="row-fluid thumbnails">
    <div class="span4 thumbnail">
        <h2><small><a href="<?= $this->url('cms', 'category', 'index') ?>">Categories</a> <span class="pull-right">(<?= $categories->count() - 1 ?>)</span></small></h2>
    </div>
    <div class="span4 thumbnail">
        <h2><small><a href="<?= $this->url('cms', 'page', 'index') ?>">Pages</a> <span class="pull-right">(<?= $pages->count() ?>)</span></small></h2>
    </div>
</div>
