<div class="row-fluid">
    <div class="span12 page-header">
        <h1><small class="text-info">Welcome <?= $this->userIdentity()->getUser()->getFirstName() ?></small></h1>
    </div>
</div>
<div class="row-fluid thumbnails">
    <div class="span12 thumbnail">
        <h2><small><a href="<?= $this->url('cms', 'article', 'index') ?>">Articles</a> <span class="pull-right">(<?= $articles->count() ?>)</span></small></h2>
    </div>
</div>
