<div class="row-fluid">
	<div class="span12">
		<h1><small class="text-error">Payment Option View</small></h1>
		<hr />
	</div>
</div>
<div class="row-fluid">
	<div class="span8 offset1">
		
			<p><span class="text-info">Name</span>: <span><?= $model->getName() ?></span></p>
			
			<p><span class="text-info">Description</span>: <span><?= $model->getDescription() ?></span></p>
			
			<p><span class="text-info">Status</span>: <span><?= $model->getStatus() ?></span></p>
			
			<p><span class="text-info">Id</span>: <span><?= $model->getId() ?></span></p>
			
	</div>
</div>
		