<?php
Table::init(array('class' => 'table table-striped data'));
Table::setHeaders(array('Email', 'Date Subscribed', ''));

foreach ($models as $model) {
    $viewBtn = '<a title="view details" href="' . $this->url('cms', 'subscription', 'view', array($model->getId())) . '" class="btn btn-mini btn-success"><i class="icon-folder-open"></i></a>';
    $editBtn = '<a title="edit" href="' . $this->url('cms', 'subscription', 'edit', array($model->getId())) . '" class="btn btn-mini btn-info"><i class="icon-edit"></i></a>';
    $deleteBtn = '<a title="delete" href="' . $this->url('cms', 'subscription', 'delete', array($model->getId())) . '" class="btn btn-mini btn-danger"><i class="icon-trash"></i></a>';

    Table::newRow();

    Table::addRowData($model->getEmail());
    Table::addRowData($model->parseDate('dateCreated'));
    Table::addRowData($deleteBtn, array('width' => '30px'));
}
?>
<div class="row-fluid">
    <div class="span12">
        <h1>
            <small class="text-error">Subscriptions</small>
        </h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <?= Table::render() ?>
    </div>
</div>
