<div class="row-fluid">
    <div class="span12">
        <h1><small class="text-error">Delete Comment</small></h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <p>All replies will be deleted too. Are you sure you want to delete this comment?</p>
        <p class="form-actions">
            <a href="<?= $this->url('cms', 'comment', 'delete', array('id' => $model->getId(), 'confirm' => 1)) ?>" class="btn btn-danger">Delete</a>
            <a href="<?= $this->url('cms', 'comment', 'index') ?>" class="btn">Cancel</a>
        </p>
    </div>
</div>
