<div class="row-fluid">
	<div class="span12">
		<h1><small class="text-error">Comment View</small></h1>
		<hr />
	</div>
</div>
<div class="row-fluid">
	<div class="span8 offset1">
		
			<p><span class="text-info">Parent</span>: <span><?= $model->getParent() ?></span></p>
			
			<p><span class="text-info">User</span>: <span><?= $model->getUser() ?></span></p>
			
			<p><span class="text-info">Article</span>: <span><?= $model->getArticle() ?></span></p>
			
			<p><span class="text-info">Content</span>: <span><?= $model->getContent() ?></span></p>
			
			<p><span class="text-info">Up Votes</span>: <span><?= $model->getUpVotes() ?></span></p>
			
			<p><span class="text-info">Down Votes</span>: <span><?= $model->getDownVotes() ?></span></p>
			
			<p><span class="text-info">Date Created</span>: <span><?= $model->getDateCreated() ?></span></p>
			
			<p><span class="text-info">Date Modified</span>: <span><?= $model->getDateModified() ?></span></p>
			
			<p><span class="text-info">Id</span>: <span><?= $model->getId() ?></span></p>
			
	</div>
</div>
		