<?php
Table::init(array('class' => 'table table-striped'));
Table::setHeaders(array('Code Name', 'Media Content (#)', ''));

foreach ($models as $model) {
    $viewBtn = '<a title="view details" href="' . $this->url('cms', 'slide', 'view', array($model->getId())) . '" class="btn btn-mini btn-success"><i class="icon-folder-open"></i></a>';
    $editBtn = '<a title="edit" href="' . $this->url('cms', 'slide', 'edit', array($model->getId())) . '" class="btn btn-mini btn-info"><i class="icon-edit"></i></a>';
    $deleteBtn = '<a title="delete" href="' . $this->url('cms', 'slide', 'delete', array($model->getId())) . '" class="btn btn-mini btn-danger"><i class="icon-trash"></i></a>';

    Table::newRow();

    Table::addRowData($model->getCodeName());
    Table::addRowData($model->media()->count());
    Table::addRowData($viewBtn . ' ' . $editBtn . ' ' . $deleteBtn, array('width' => '100px'));
}
?>
<div class="row-fluid">
    <div class="span12">
        <h1>
            <small class="text-error">Slide Sets</small>
            <a href="<?= $this->url('cms', 'slide', 'new') ?>" class="btn btn-success pull-right">New Slide Set</a>
        </h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span6 offset1">
        <?= Table::render() ?>
    </div>
</div>
