<?php
ob_start();

$carousel = array();
foreach ($models as $key => $model) {
    $img = $this->fo($model->getPath());

    $carousel[$model->getId()] = array(
        'img' => $img,
        'caption' => $model->getDescription()
    );
    ?>
    <div data-id="<?= $model->getId() ?>" class="thumbnail span3">
        <?= $img ?>
    </div>
    <?php
    if (($key + 1) % 4 === 0) {
        ?>
        </div>
        <div class="row-fluid thumbnails">
            <?php
        }
    }
    $thumbnails = ob_get_clean();
    ?>
    <div class="row-fluid">
        <div class="span12" style="position:relative">
            <h1 class="page-header">
                <small class="text-error">Media</small>
                <a href="<?= $this->url('cms', 'media', 'new') ?>" class="btn btn-success pull-right">New Media</a>
            </h1>
            <?=
            TwBootstrap::customModal(array(
                'modalId' => 'modalImage',
                'content' => TwBootstrap::carousel($carousel, array('id' => 'imgCarousel'))
                    ), false)
            ?>
        </div>
    </div>
    <div class="row-fluid thumbnails">
        <?= $thumbnails ?>
    </div>
    <script>
        $(function() {
            $('.thumbnail > img').live('click', function() {
                $('#imgCarousel .active').removeClass('active');
                $('#imgCarousel #' + $(this).parent().attr('data-id')).addClass('active');
                $('#modalImage').modal('show');
            });
            $('#modalImage').live('shown', function() {
                $(this).css({
                    position: 'absolute',
                    width: '100%',
                    height: window.screen.availHeight - 200,
                    top: 0,
                    left: 0,
                    margin: 0,
                });

                var modalBody = $(this).children('.modal-body');

                $(modalBody).css({
                    height: $(this).height(),
                    width: $(modalBody).width() - 1,
                    'max-height': $(this).height() - 20,
                });

                $('#imgCarousel img').css({
                    'max-height': $(modalBody).height() - 10,
                });
            });
        });
    </script>