<div class="row-fluid">
    <div class="span12">
        <h1><small class="text-error">New Media</small></h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span8 offset2">
        <?= $form->setAttribute('action', $this->currentPath())->render() ?>
    </div>
</div>
<script>
    $(function() {
        $('form#<?= $form->getName() ?> input[type="submit"]').parent().append('<input class="btn btn-primary" type="submit" name="saveAndNew" value="Save and Add New" />')
    });
</script>