<div class="row-fluid">
    <div class="span12">
        <h1><small class="text-error">Media</small></h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span2 offset2">
        <?= $this->fo($model->getPath()) ?>
    </div>
    <div class="span6">
        <h3 class="page-header"><small class="text-info">Name</small><small>: <?= $model->getName() ?></small></h3>
        <p>
            <?= $model->getDescription() ?>
        </p>
    </div>
</div>
