<div class="row-fluid">
    <div class="span12">
        <h1><small class="text-error">Edit Password</small></h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span2">
        <?php
        $fo = new FileOut();
        echo $fo($model->getPicture(), array(
            'attrs' => array(
                'alt' => 'Picture: ' . $model->getFullName(),
                'class' => 'img-polaroid'
            )
        ))
        ?>        
    </div>
    <div class="span8">
        <?= TwbForm::horizontal($form->setAttribute('action', $this->currentPath())) ?>
    </div>
</div>
