<?php
Table::init(array('class' => 'table table-striped data'));
Table::setHeaders(array('', 'First Name', 'Last Name', 'Email', 'Role', ''));

foreach ($models as $model) {
    if ($this->userIdentity()->getUser()->getId() === $model->getId())
        continue;

    $viewBtn = TwBootstrap::customModal(array(
                'href' => $this->url('cms', 'user', 'view', array('id' => $model->getId())),
                'linkLabel' => '<i class="icon-folder-open"></i>',
                'linkAttrs' => array(
                    'class' => 'btn btn-success',
                    'title' => 'view details'
                ),
    ));

    $editBtn = TwBootstrap::customModal(array(
                'href' => $this->url('cms', 'user', 'edit', array('id' => $model->getId())),
                'linkLabel' => '<i class="icon-edit"></i>',
                'linkAttrs' => array(
                    'class' => 'btn btn-info',
                    'title' => 'edit'
                ),
    ));

    $deleteBtn = TwBootstrap::customModal(array(
                'href' => $this->url('cms', 'user', 'delete', array('id' => $model->getId())),
                'linkLabel' => '<i class="icon-trash"></i>',
                'linkAttrs' => array(
                    'class' => 'btn btn-danger',
                    'title' => 'delete'
                ),
    ));

    Table::newRow();

    $fo = new FileOut();
    Table::addRowData($fo($model->getPicture(), array(
                'attrs' => array(
                    'alt' => 'Picture: ' . $model->getFullName()
                )
            )), array('width' => '40px'));
    Table::addRowData($model->getFirstName());
    Table::addRowData($model->getLastName());
    Table::addRowData('<a title="send a mail with your email client" href="mailto:' . $model->getEmail() . '">' . $model->getEmail() . '</a>');
    Table::addRowData($model->getRole());
    Table::addRowData($viewBtn . ' ' . $editBtn . ' ' . $deleteBtn, array('width' => '150px'));
}

echo TwBootstrap::customModal(array(
    'href' => $this->url('cms', 'user', 'new'),
    'linkLabel' => 'New User',
    'linkAttrs' => array(
        'class' => 'btn btn-success',
    ),
    'modalId' => 'newUser',
        ), false);
?>
<style>
    td {
        vertical-align: middle!important;
    }
</style>
<div class="row-fluid">
    <div class="span12">
        <h1>
            <small class="text-info">Users</small>
            <?= TwBootstrap::modalLink('newUser') ?>
        </h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <?= Table::render() ?>
    </div>
</div>
