<div class="row-fluid">
    <div class="span12">
        <h1>
            <small class="text-error">User Profile</small>
            <a class="btn btn-info" href="<?= $this->url('cms', 'user', 'edit-profile') ?>">Edit <i class="icon-edit icon-white"></i></a>
        </h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span2">
        <?php
        $fo = new FileOut();
        echo $fo($model->getPicture(), array(
            'attrs' => array(
                'alt' => 'Picture: ' . $model->getFullName(),
                'class' => 'img-polaroid'
            )
        ))
        ?>
    </div>
    <div class="span8">
        <div class="row-fluid" style="margin-bottom:5px!important">
            <div class = "badge badge-info span3">First Name:</div> <div class="span9"><?= $model->getFirstName() ?></div>
        </div>
        <div class="row-fluid" style="margin-bottom:5px!important">
            <div class = "badge badge-info span3">Last Name:</div> <div class="span9"><?= $model->getLastName() ?></div>
        </div>
        <div class="row-fluid" style="margin-bottom:5px!important">
            <div class = "badge badge-info span3">Email Address:</div> <div class="span9"><?= $model->getEmail() ?></div>
        </div>
        <div class="row-fluid" style="margin-bottom:5px!important">
            <div class = "badge badge-info span3">Register Date:</div> <div class="span9"><?= $model->parseDate('registerDate') ?></div>
        </div>
        <div class="row-fluid" style="margin-bottom:5px!important">
            <div class = "badge badge-info span3">Last Login Date:</div> <div class="span9"><?= $model->parseDate('lastLogin') ?></div>
        </div>
    </div>
</div>
