<div class="row-fluid">
    <div class="span12">
        <h1>
            <small class="text-error">User Profile</small>
            <a class="btn btn-info" href="<?= $this->url('cms', 'user', 'edit-profile') ?>">Edit <i class="icon-edit icon-white"></i></a>
        </h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span2">
        <?php
        $fo = new FileOut();
        echo $fo($model->getPicture(), array(
            'attrs' => array(
                'alt' => 'Picture: ' . $model->getFullName(),
                'class' => 'img-polaroid'
            )
        ))
        ?>
    </div>
    <div class="span8">
        <div class="row-fluid">
            <div class="span3">
                <span class="badge badge-info">First Name:</span>
            </div>
            <div class="span9">
                <?= $model->getFirstName() ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span3">
                <span class="badge badge-info">Last Name:</span>
            </div>
            <div class="span9">
                <?= $model->getLastName() ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span3">
                <span class="badge badge-info">Email:</span>
            </div>
            <div class="span9">
                <?= $model->getEmail() ?>
            </div>
        </div>
    </div>
</div>
