<div class="row-fluid">
    <div class="span12">
        <h1>
            <small class="text-error">User <?= $model->getFullName() ?></small>
        </h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span2">
        <?php
        $fo = new FileOut;
        echo $fo($model->getPicture(), array(
            'attrs' => array(
                'alt' => 'Picture: ' . $model->getFullName(),
                'class' => 'img-polaroid'
            )
        ))
        ?>
    </div>
    <div class="span8">
        <div class="row-fluid" style="margin-bottom:5px!important">
            <div class = "badge badge-info span3">Email:</div> <a title="send email" href="mailto:<?= $model->getEmail() ?>" class="span9"><?= $model->getEmail() ?></a>
        </div>
        <div class="row-fluid" style="margin-bottom:5px!important">
            <div class = "badge badge-info span3">Register Date:</div> <div class="span9"><?= $model->parseDate('registerDate') ?></div>
        </div>
        <div class="row-fluid" style="margin-bottom:5px!important">
            <div class = "badge badge-info span3">Last Login Date:</div> <div class="span9"><?= $model->parseDate('lastLogin') ?></div>
        </div>
        <div class="row-fluid" style="margin-bottom:5px!important">
            <div class = "badge badge-info span3">Role:</div> <div class="span9"><?= $model->getRole() ?></div>
        </div>
    </div>
</div>