<div class="row-fluid">
	<div class="span12">
		<h1><small class="text-error">Delete Category</small></h1>
		<hr />
	</div>
</div>
<div class="row-fluid">
	<div class="span8 offset1">
		<p>Are you sure you want to delete?</p>
		<p class="form-actions">
			<a href="<?= $this->url('store','category','delete', array('id' => $model->getId(), 'confirm' => 1)) ?>" class="btn btn-danger">Delete</a>
			<a href="<?= $this->url('store','category','index') ?>" class="btn">Cancel</a>
		</p>
	</div>
</div>
		