<style>
    .thumbnail {
        text-align: center;
        height:190px;
        position:relative;
        overflow-y:hidden;
    }
    .thumbnail img {
        width:100%;
        margin-bottom: 10px;
    }
    .thumbnail .actions,
    .thumbnail .desc {
        display:none;
    }
    .thumbnail:hover {
        background-color:#eee;
    }
    .thumbnail:hover img {
        height:0;
    }
    .thumbnail:hover .actions,
    .thumbnail:hover .desc{
        display:block;
    }
    .thumbnail h3 {
        margin:0;   
    }
    .thumbnail h3 a {
        text-decoration: none;
    }
    .thumbnail hr {
        margin-top:0;
        margin-bottom:0px;
    }
</style>
<?php if (!$this->userIdentity()->isGuest()): ?>
    <div class="row-fluid">
        <div class="span12">
            <h1>
                <small class="text-error">Categories</small>
                <a href="<?= $this->url('store', 'category', 'new') ?>" class="btn btn-success pull-right">New Category</a>
            </h1>
            <hr />
        </div>
    </div>
<?php endif; ?>
<div class="row-fluid">
    <ul class="thumbnails">
        <?php
        foreach ($models as $key => $model) {
            ?>
            <li class="span3">
                <div class="thumbnail">
                    <h3><a href="<?= $this->url('store', 'category', 'items', array($model->getLink())) ?>" class="text-error"><?= $model->getName() ?></a></h3>
                    <hr />
                    <?php if ($model->getImage(true)): ?>
                        <img src="<?= $model->getThumbnails('image', 0) ?>" alt="Category <?= $model->getName() ?>" />
                    <?php endif; ?>
                    <?php if (!$this->userIdentity()->isGuest()): ?>
                        <div class="actions">
                            <a href="<?= $this->url('store', 'category', 'edit', array($model->getId())) ?>">edit</a> | 
                            <a href="<?= $this->url('store', 'category', 'delete', array($model->getId())) ?>">delete</a>
                        </div>
                    <?php endif; ?>
                    <?php if ($model->getDescription()): ?>
                        <p class="desc"><?= $model->getDescription() ?></p>
                    <?php endif; ?>
                </div>
            </li>
            <?php
            if ($key && $key % 4 === 0):
                ?>
            </ul>
        </div>
        <div class="row-fluid">
            <ul class="thumbnails">
                <?php
            endif;
        }
        ?>
    </ul>
</div>
