<?php
//foreach ($items as $item) {
//    $editBtn = '<a title="edit" href="' . $this->url('store', 'item', 'edit', array($item->getId())) . '">edit</a>';
//    $deleteBtn = '<a title="delete" href="' . $this->url('store', 'item', 'delete', array($item->getId())) . '">delete</a>';
//
//    Table::newRow();
//
//    Table::addRowData('<a title="view details" href="' . $this->url('store', 'item', 'view', array($item->getId())) . '">' . $item->getName() . '</a>');
//    Table::addRowData($item->getShortDescription());
//    Table::addRowData($editBtn . ' ' . $deleteBtn, array('width' => '100px'));
//}
?>
<style>
    .thumbnail {
        text-align: center;
        height:190px;
        position:relative;
        overflow-y:hidden;
    }
    .thumbnail img {
        width:100%;
        margin-bottom: 10px;
    }
    .thumbnail .actions,
    .thumbnail .desc,
    .thumbnail .add-to-cart {
        display:none;
    }
    .thumbnail:hover {
        background-color:#eee;
    }
    .thumbnail:hover img {
        height:0;
    }
    .thumbnail:hover .actions,
    .thumbnail:hover .desc,
    .thumbnail .add-to-cart {
        display:block;
    }
    .thumbnail h3 {
        margin:0;   
    }
    .thumbnail h3 a {
        text-decoration: none;
    }
    .thumbnail hr {
        margin-top:0;
        margin-bottom:0px;
    }
</style>
<div class="row-fluid">
    <div class="span12">
        <h1>
            <small class="text-success"><?= $category->getName() ?></small>
            <a href="<?= $this->url('store', 'item', 'new', array($category->getLink())) ?>" class="btn btn-success pull-right">New Item</a>
        </h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <ul class="thumbnails">
        <?php
        foreach ($category->item(array(
            'orderBy' => 'name'
        )) as $key => $item) {
            if ($item->getName() == 750) {
                echo '<pre>';
                die(print_r($item->getThumbnails('images')));
            }
            ?>
            <li class="span3">
                <div class="thumbnail">
                    <h3>
                        <a href="<?= $this->url('store', 'item', 'view', array($category->getLink(), $item->getLink())) ?>"
                           class="text-error"><?= $item->getName() ?></a>
                    </h3>
                    <hr />
                    <?php if ($item->getImages(true)): ?>
                                                    <!--<img src="<?= $item->getThumbnails('images', 0) ?>" alt="Category <?= $item->getName() ?>" />-->
                    <?php endif; ?>
                    <?php if ($this->userIdentity()->isGuest()): ?>
                        <div class="actions">
                            <a href="<?= $this->url('store', 'item', 'edit', array($category->getLink(), $item->getLink())) ?>">edit</a> | 
                            <a href="<?= $this->url('store', 'item', 'delete', array($category->getLink(), $item->getLink())) ?>">delete</a>
                        </div>
                    <?php endif; ?>
                    <a href="#" class="btn btn-link btn-info add-to-cart"><i class="icon-shopping-cart"></i> Add to cart</a>
                    <?php if ($item->getShortDescription()): ?>
                        <p class="desc"><?= $item->getShortDescription() ?></p>
                    <?php endif; ?>
                </div>
            </li>
            <?php
            if ($key && $key % 4 === 0):
                ?>
            </ul>
        </div>
        <div class="row-fluid">
            <ul class="thumbnails">
                <?php
            endif;
        }
        ?>
    </ul>
</div>