<?php
ob_start();
$this->loadAsset('img/glyphicons-halflings.png')
        ->loadAsset('img/glyphicons-halflings-white.png');

echo $this->loadCss('css/bootstrap.min');
echo $this->loadCss('css/demo_table');
echo $this->loadCss('css/dscribe');
echo $this->loadCss('css/bootstrap-responsive.min');

echo $this->loadJs('js/jquery-2.0.2.min');
echo $this->loadJs('js/jquery-migrate-1.2.1.min');
echo $this->loadJs('js/bootstrap.min');
echo $this->loadJs('js/jquery-ui');
echo $this->loadJs('js/jquery.dataTables.min');
?>
<style>
    body {
        position:relative;
        margin-top:60px;
        margin-bottom:100px;
    }

    .sidenav ul {
        margin-bottom:0;
        -webkit-border-radius: 6px;
        -moz-border-radius: 6px;
        border-radius: 6px;
        -webkit-box-shadow: 0 1px 4px rgba(0,0,0,.065);
        -moz-box-shadow: 0 1px 4px rgba(0,0,0,.065);
        box-shadow: 0 1px 4px rgba(0,0,0,.065);
    }
    .sidenav > li > a {
        display: block;
        width: 190px \9;
        margin: 0 0 -1px;
        padding: 8px 14px;
        border: 1px solid #e5e5e5;
    }
    .sidenav > li:first-child > a {
        -webkit-border-radius: 6px 6px 0 0;
        -moz-border-radius: 6px 6px 0 0;
        border-radius: 6px 6px 0 0;
    }
    .sidenav > li:last-child > a {
        -webkit-border-radius: 0 0 6px 6px;
        -moz-border-radius: 0 0 6px 6px;
        border-radius: 0 0 6px 6px;
    }
    .sidenav > .active > a {
        position: relative;
        z-index: 2;
        padding: 9px 15px;
        border: 0;
        text-shadow: 0 1px 0 rgba(0,0,0,.15);
        -webkit-box-shadow: inset 1px 0 0 rgba(0,0,0,.1), inset -1px 0 0 rgba(0,0,0,.1);
        -moz-box-shadow: inset 1px 0 0 rgba(0,0,0,.1), inset -1px 0 0 rgba(0,0,0,.1);
        box-shadow: inset 1px 0 0 rgba(0,0,0,.1), inset -1px 0 0 rgba(0,0,0,.1);
    }
    /* Chevrons */
    .sidenav .icon-chevron-right {
        float: right;
        margin-top: 2px;
        margin-right: -6px;
        opacity: .25;
    }
    .sidenav > li > a:hover {
        background-color: #f5f5f5;
    }
    .sidenav a:hover .icon-chevron-right {
        opacity: .5;
    }
    .sidenav .active .icon-chevron-right,
    .sidenav .active a:hover .icon-chevron-right {
        /*background-image: url(../img/glyphicons-halflings-white.png);*/
        /*opacity: 1;*/
    }
    /*    .sidenav.affix {
            top: 40px;
        }*/
</style>
<div class="row">
    <div class="span3 sidenav">
        <a class="btn btn-navbar hidden-desktop btn-warning" data-toggle="collapse" data-target=".nav-collapse"><i class="icon-list icon-white"></i> Menu</a>
        <div class="nav-collapse collapse affix-top">
            <ul class="nav nav-tabs nav-stacked">
                <?= @$nav ?>
                <li class="dropdown <?= ($this->controller() === 'user' && in_array($this->action(), array('profile', 'edit-profile', 'edit-password'))) ? 'active' : '' ?>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i> <i class="icon-chevron-right"></i> Me</a>
                    <ul class="dropdown-menu">
                        <li class="<?= ($this->controller() == 'user' && in_array($this->action(), array('profile', 'edit-profile', 'edit-password'))) ? 'active' : '' ?>"><a href=" <?= $this->url('cms', 'user', 'profile') ?>"><i class="icon-briefcase"></i> Profile</a></li>
                        <li class="divider"></li>
                        <li><a href=" <?= $this->url('cms', 'guest', 'logout') ?>"><i class="icon-off"></i> Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <div class="span9">
        <?= $content ?>
    </div>
</div>
<script>
    $(document).ready(function() {
//        $('.sidenav').affix({
//            offset: {
//                top: 10
//            }
//        });


        $('.data').dataTable({
            "sPaginationType": "full_numbers"
        });
    });
</script>
<?php
$this->loadLayout('users', array(
    'content' => ob_get_clean(),
));
