<?php
$groups = array();
foreach ($groupedArticles as $category => $articlesArray) {
    $group = array(
        'heading' => $category,
    );
    ob_start();
    ?>
    <div class="container-fluid">
        <div class="row-fluid thumbnails">
            <?php
            foreach ($articlesArray as $key => $article) {
                if ($key > 4)
                    break;
                ?>
                <div class="span3 thumbnail" style="height:120px;">
                    <h2><small><a href="<?= $this->url('cms', 'article', 'view', array($article->getCategoryLink(), $article->getLink())) ?>"><?= $article->getTitle() ?></a></small></h2>
                    <p><?= Util::shortenString(strip_tags($article->getContent())) ?></p>
                </div>
                <?php
            }
            ?>
        </div>
        <?php if (count($articlesArray) > 4): ?>
            <div class="row-fluid" style="margin-top:15px;">
                <div class="span12">
                    <a class="btn-link text-success" href="<?= $this->url('cms', 'article', 'view-category', array($article->getCategoryLink())) ?>">see all articles</a>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <?php
    $group['body'] = ob_get_clean();
    $groups[] = $group;
}

ob_start()
?>
<style>
    .accordion-heading {
        font-size:large;
        font-weight:bolder;
        background-color:#f5f5f5;
    }
</style>
<div class="row-fluid">
    <div class="span9">
        <?= TwBootstrap::accordion($groups, array('close' => true)) ?>
    </div>
    <div class="span3">
        <div class="row-fluid">
            <div class="span12 well well-small text-info">
                Subscribe here
                <?= CMS::createSubscriptionForm() ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12 well well-small thumbnail">
                <h3><small class="text-error">Most Recent Articles</small></h3>
                <?= CMS::createArticleLinks(5, array('class' => 'nav nav-tabs nav-stacked')) ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12 well well-small">
                <h3><small class="text-error">Other Categories <a class="btn-link text-warning" style="font-style:italic" href="<?= $this->url('cms', 'article', 'list-categories') ?>">(view all)</a></small></h3>
                <?= CMS::createArticleCategoryLinks(5, array('class' => 'nav nav-tabs nav-stacked')) ?>
            </div>
        </div>
    </div>
</div>
<?php
$this->loadLayout(DScribe\Core\Engine::getDefaultLayout(), array(
    'content' => ob_get_clean(),
));
