<?php
$this->loadAsset('img/glyphicons-halflings.png')->loadAsset('img/glyphicons-halflings-white.png')->loadAsset('img/logo.png');
?>
<!DOCTYPE>
<html>
    <head>
        <title>DScribe | CMS</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?= $this->loadCss('css/bootstrap.min') ?>
        <?= $this->loadCss('css/bootstrap-responsive.min') ?>
        <?= $this->loadCss('css/demo_table') ?>
        <?= $this->loadCss('css/dscribe') ?>
        <?= $this->loadIcon('img/logo.png') ?>
        <?= $this->loadJs('js/jquery.min') ?>
        <style>
            body {
                position:relative;
                margin-top:60px;
                margin-bottom:100px;
            }
            
            .navbar-fixed-bottom {
                height:40px;
            }
            
            .navbar-fixed-bottom hr {
                margin-bottom: 10px;
                border-color:#000;
            }
        </style>
    </head>
    <body>
        <div class="container-fluid">
            <header>
                <div class="navbar navbar-inverse navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container">
                            <div class="row">
                                <div class="span12">
                                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </a>
                                    <a href="<?= $this->home() ?>" class="brand"><?= $this->name ?></a>
                                    <ul class="nav pull-right">
                                        <li class="dropdown <?= (in_array($this->controller(), array('user', 'preferences'))) ? 'active' : '' ?>">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> Me</a>
                                            <ul class="dropdown-menu">
                                                <li><a href="<?= $this->url('cms', 'user', 'profile') ?>"><i class="icon-briefcase"></i> Profile</a></li>
                                                <li class="divider"></li>
                                                <li><a href="<?= $this->url('cms', 'guest', 'logout') ?>"><i class="icon-off"></i> Logout</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                    <div class="nav-collapse collapse">
                                        <ul class="nav">
                                            <?= @$nav ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <?php
            if ($this->flash()->hasMessage()) {
                ?>
                <div class="row-fluid">
                    <div class="span10 offset1">
                        <div class="alert alert-<?= ($this->flash()->hasErrorMessage()) ? 'error' : 'success' ?> no-close" style="text-align:center">
                            <?=
                            $this->flash()->hasErrorMessage() ? $this->flash()->getErrorMessage() :
                                    $this->flash()->getSuccessMessage()
                            ?>
                        </div>
                    </div>
                </div>
                <?php
            }
            ?>
            <div class="row-fluid">
                <div class="span10 offset1">
                    <div class="container-fluid">
                        <div class="row-fluid">
                            <?= $content ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="navbar-fixed-bottom">
                <hr />
                <div class="container">
                    <footer class="footer">
                        &copy; 2014 <a target="_blank" href="http://ezraobiwale.com/dscribe">DScribe</a>
                    </footer>
                </div>
            </div>
        </div>
        <?= $this->loadJs('js/jquery-ui') ?>
        <?= $this->loadJs('js/jquery.dataTables.min') ?>
        <?= $this->loadJs('js/jquery.ui.datepicker.min') ?>
        <?= $this->loadJs('js/jquery.timepicker.min') ?>
        <?= $this->loadJs('js/jquery.form') ?>
        <?= $this->loadJs('js/bootstrap.min') ?>
        <?= $this->loadJs('js/dscribe') ?>
        <script>
            $(document).ready(function() {
                $('.disabled').live('click', function(e) {
                    e.preventDefault();
                });

                $('.data').dataTable();
            });
        </script>
    </body>
</html>