<?php
$this->loadAsset('img/glyphicons-halflings.png')->loadAsset('img/glyphicons-halflings-white.png')->loadAsset('img/logo.png');
?>
<!DOCTYPE>
<html>
    <head>
        <title>DScribe CMS - <?= CMS::getSiteName() ?></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?= $this->loadCss('css/bootstrap.min') ?>
        <?= $this->loadCss('css/demo_table') ?>
        <?= $this->loadCss('css/jquery.ui.core.min') ?>
        <?= $this->loadCss('css/jquery.ui.datepicker.min') ?>
        <?= $this->loadCss('css/jquery.timepicker') ?>
        <?= $this->loadCss('css/dscribe') ?>
        <?= $this->loadIcon('images/logo') ?>
        <?= $this->loadJs('js/jquery.min') ?>
        <style>
            body {
                position:relative;
                padding-top:80px;
                padding-bottom:100px;
            }

            .navbar-fixed-bottom {
                height:40px;
            }

            .navbar-fixed-bottom hr {
                margin-bottom: 10px;
                border-color:#000;
            }

            .brand img {

            }

            .nav img {
                width:25px;
            }
        </style>
        <?= $this->loadCss('css/bootstrap-responsive.min') ?>
    </head>
    <body>
        <div class="container-fluid">
            <header>
                <div class="navbar navbar-inverse navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container">
                            <div class="row">
                                <div class="span12">
                                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </a>
                                    <a href="<?= $this->home() ?>" class="brand">
                                        <?= CMS::getSiteName() ?>
                                    </a>
                                    <ul class="nav pull-right">
                                        <li class="dropdown <?= (in_array($this->controller(), array('user', 'preferences'))) ? 'active' : '' ?>">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                <?php if ($this->userIdentity()->getUser()->getPicture()): ?>
                                                    <img src="<?= $this->userIdentity()->getUser()->getPicture() ?>" /> Me
                                                <?php else:
                                                    ?>
                                                    <i class="icon-user icon-white"></i> Me
                                                <?php endif; ?>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li><a href="<?= $this->url('cms', 'user', 'profile') ?>"><i class="icon-briefcase"></i> Profile</a></li>
                                                <li class="divider"></li>
                                                <li><a href="<?= $this->url('cms', 'guest', 'logout') ?>"><i class="icon-off"></i> Logout</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                    <div class="nav-collapse collapse">
                                        <ul class="nav">
                                            <?= @$nav ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <div class="row-fluid">
                <div class="span10 offset1">
                    <?php if ($this->flash()->hasMessage()): ?>
                        <div class="row-fluid">
                            <div class="span12 alert alert-info" style="text-align:center">
                                <?= $this->flash()->getMessage() ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if ($this->flash()->hasSuccessMessage()): ?>
                        <div class="row-fluid">
                            <div class="span12 alert alert-success" style="text-align:center">
                                <?= $this->flash()->getSuccessMessage() ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if ($this->flash()->hasErrorMessage()): ?>
                        <div class="row-fluid">
                            <div class="span12 alert alert-error" style="text-align:center">
                                <?= $this->flash()->getErrorMessage() ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="row-fluid">
                        <?= $content ?>
                    </div>
                </div>
            </div>
            <div class="navbar-fixed-bottom">
                <hr />
                <div class="container">
                    <footer class="footer">
                        &copy; 2014 <a target="_blank" href="http://dscribe.ezraobiwale.com/modules/cms">DScribe Framework CMS</a>
                    </footer>
                </div>
            </div>
        </div>
        <?= $this->loadJs('js/jquery-ui') ?>
        <?= $this->loadJs('js/jquery.dataTables.min') ?>
        <?= $this->loadJs('js/jquery.ui.datepicker.min') ?>
        <?= $this->loadJs('js/jquery.timepicker.min') ?>
        <?= $this->loadJs('js/jquery.form') ?>
        <?= $this->loadJs('js/bootstrap.min') ?>
        <?= $this->loadJs('js/dscribe') ?>
        <script>
            $(document).ready(function() {
                $('.disabled').live('click', function(e) {
                    e.preventDefault();
                });

                $('.data').dataTable();
            });
        </script>
    </body>
</html>
