<?php
Table::init(array('class' => 'table table-striped'));
Table::setHeaders(array('Title', 'Link', 'Date Created', ''));

foreach ($models as $model) {
    $viewBtn = '<a title="view details" href="' . $this->url('cms', 'newsletter', 'view', array($model->getId())) . '" class="btn btn-mini btn-success"><i class="icon-folder-open"></i></a>';
    $editBtn = '<a title="edit" href="' . $this->url('cms', 'newsletter', 'edit', array($model->getId())) . '" class="btn btn-mini btn-info"><i class="icon-edit"></i></a>';
    $deleteBtn = '<a title="delete" href="' . $this->url('cms', 'newsletter', 'delete', array($model->getId())) . '">delete</a>';

    Table::newRow();

    Table::addRowData($model->getTitle());
    Table::addRowData($model->getLink());
    Table::addRowData($model->parseDate('dateCreated'));
    Table::addRowData($editBtn . ' ' . $deleteBtn, array('width' => '100px'));
}
?>
<div class="row-fluid">
    <div class="span12">
        <h1>
            <small class="text-error">Newsletters</small>
            <a href="<?= $this->url('cms', 'newsletter', 'new') ?>" class="btn btn-success pull-right">New Newsletter</a>
        </h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <?= Table::render() ?>
    </div>
</div>
