<div class="row-fluid">
	<div class="span12">
		<h1><small class="text-error">Newsletter View</small></h1>
		<hr />
	</div>
</div>
<div class="row-fluid">
	<div class="span8 offset1">
		
			<p><span class="text-info">Author</span>: <span><?= $model->getAuthor() ?></span></p>
			
			<p><span class="text-info">Title</span>: <span><?= $model->getTitle() ?></span></p>
			
			<p><span class="text-info">Link</span>: <span><?= $model->getLink() ?></span></p>
			
			<p><span class="text-info">Content</span>: <span><?= $model->getContent() ?></span></p>
			
			<p><span class="text-info">Date Created</span>: <span><?= $model->getDateCreated() ?></span></p>
			
			<p><span class="text-info">Id</span>: <span><?= $model->getId() ?></span></p>
			
	</div>
</div>
		