<div class="row-fluid">
	<div class="span12">
		<h1><small class="text-error">Social View</small></h1>
		<hr />
	</div>
</div>
<div class="row-fluid">
	<div class="span8 offset1">
		
			<p><span class="text-info">Name</span>: <span><?= $model->getName() ?></span></p>
			
			<p><span class="text-info">Link</span>: <span><?= $model->getLink() ?></span></p>
			
			<p><span class="text-info">Image</span>: <span><?= $model->getImage() ?></span></p>
			
			<p><span class="text-info">Id</span>: <span><?= $model->getId() ?></span></p>
			
	</div>
</div>
		