<div class="row-fluid">
    <div class="span12">
        <h1><small class="text-error">Delete Category <span class="text-success"><?= $model->getName() ?></span></small></h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span12 text-info">
        <p>All pages in this category will be lost. Are you sure you want to delete this category?</p>
        <p class="form-actions">
            <a href="<?= $this->url('cms', 'category', 'delete', array('id' => $model->getId(), 'confirm' => 1)) ?>" class="btn btn-danger">Delete</a>
            <a href="<?= $this->url('cms', 'page', 'index', array(), $model->getId()) ?>" class="btn">Cancel</a>
        </p>
    </div>
</div>
