<?=
TwBootstrap::customModal(array(
    'href' => '/cms/category/form-list/' . $categoryId,
    'linkLabel' => 'Select Category',
    'linkAttrs' => array(
        'class' => 'btn btn-success btn-category btn-mini hidden',
        'style' => 'margin-left:10px'
    ),
    'modalId' => 'cms-page-modal',
    'header' => '
    <h1 class="text-success clear">
        <small>Page Categories</small>
    </h1>'
        ), true);
?>
<div class="row-fluid">
    <div class="span12">
        <h1><small class="text-error"><?= $type ?> Category</small></h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <?= TwbForm::horizontal($form) ?>
    </div>
</div>
<script>
    $(function() {
        if ('<?= $type ?>' == 'New')
            $('form#categoryForm input[type="submit"]').parent().append('<input class="btn btn-primary" type="submit" name="saveAndNew" style="margin-right:5px" value="Save and Add New" /><input class="btn btn-info" type="submit" name="saveAndNewPage" value="Save and Add Page" />')
        $('#name').live('keyup blur', function() {
            $('#link').val($(this).val().replace(/[A-Z]+/g, function(l) {
                return l.toLowerCase();
            }).replace(/[^a-z0-9-\s]*/g, '').replace(/\s/g, '-').replace('--', '-'));
        });

        var cat = $('form#categoryForm select#parent').hide().parent();
        $(cat).append('<span class="badge badge-info" id="currentCategory">' + $('form#categoryForm select#parent > option[value="' +
                $('form#categoryForm select#parent').val() + '"]').html() + '</span>')
                .append($('.btn-category')
                        .removeClass('hidden')
                        .attr('href', $('.btn-category').attr('href') + '/' +
                                $('form#categoryForm select#parent').children().val() +
                                '/' + $('form#categoryForm select#parent').val()));

        // get the selected value from category list
        $('.categoryValue').live('click', function(e) {
            e.preventDefault();
            $('form#categoryForm select#parent').val($(this).attr('data-value'));

            $('#currentCategory').html($(this).html());

            $('form#categoryForm a.btn-category').attr('href', '/cms/category/form-list/' + $(this).attr('data-value'));
        });
    });
</script>
