<?php ob_start() ?>
<div class="row-fluid">
    <div class="span7 offset1 well well-small bg-img">
        <div class="row-fluid">
            <div class="span12">
                <h1>
                    <small class="text-error"><?= $articles->first()->getCategory() ?></small>
                </h1>
            </div>
        </div>
        <hr />
        <div class="row-fluid">
            <div class="span12">
                <?php
                $items = array();
                foreach ($articles as $key => $article) {
                    ob_start();
                    ?>
                    <h2 class="page-header">
                        <small><a href="<?= $this->url('cms', 'article', 'view', array($article->getCategoryLink(), $article->getLink())) ?>"><?= $article->getTitle() ?></a></small>
                        <small class="pull-right" style="font-size:12px"><?= \DBScribe\Util::createTimestamp($article->getDateModified(), 'jS M, Y') ?></small>
                    </h2>
                    <p><?= Util::shortenString(strip_tags($article->getContent()), 200) ?></p>
                    <?php
                    $items[] = ob_get_clean();
                }

                echo TwBootstrap::groupIntoRows($items, 2, array(
                    'spans' => array(
                        'class' => 'thumbnail well well-small'
                    ),
                    'rows' => array(
                        'class' => 'thumbnails',
                        'style' => 'margin-bottom:20px'
                    )
                ));
                ?>
            </div>
        </div>
    </div>
    <div class="span3">
        <div class="row-fluid">
            <div class="span12 well well-small text-info bg-img">
                Subscribe here
                <?= CMS::createSubscriptionForm() ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12 well well-small bg-img">
                <h3><small class="text-error">Most Recent Articles</small></h3>
                <?= CMS::createArticleLinks(5, array('class' => 'nav nav-tabs nav-stacked well well-small')) ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12 well well-small bg-img">
                <h3><small class="text-error">Other Categories <a class="btn-link text-warning" style="font-style:italic" href="<?= $this->url('cms', 'article', 'list-categories') ?>">(view all)</a></small></h3>
                <?= CMS::createArticleCategoryLinks(5, array('class' => 'nav nav-tabs nav-stacked well well-small')) ?>
            </div>
        </div>
    </div>
</div>
<?php
$this->loadLayout('rosey/cms-main', array(
    'content' => ob_get_clean(),
));
