<?php
$this->loadAsset('rosey/img/glyphicons-halflings.png')->loadAsset('rosey/img/glyphicons-halflings-white.png');
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?= CMS::getSiteName() . ' | ' . CMS::getTitle() ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="<?= CMS::getDescription() ?>">
        <meta name="author" content="Ezra Obiwale <ezraobiwale.com>">

        <!-- Le styles -->
        <link href="<?= $this->getAsset('rosey/css/bootstrap.min.css') ?>" rel="stylesheet">
        <script src="<?= $this->getAsset('rosey/js/jquery.min.js') ?>"></script>
        <style>
            html {
                height:100%;
                width:100%;
            }
            body {
                height:100%;
                background:url('<?= $this->getAsset('rosey/images/custom-2.png') ?>');
                color:#5e2d79;
                margin-bottom:250px;
            }

            header.navbar {
                background-color:#5e2d79;
                color:#fff9f0!important;
                font-family: verdana,monospace;
                font-size:large;
                font-weight: bold;
                height:100px;
                margin-bottom:50px;
            }
            header h1 {
                margin:27px 0;
                padding-left:220px;
                color:#fff9f0!important;
            }
            header img {
                width:200px;
                padding:0px;
                max-height:120px;
            }

            .nav-collapse {
                text-align: center;
            }

            .nav-pills {
                margin-left:15px!important;
            }

            .nav-pills a {
                color:#5e2d79!important;
                font-size:small;
            }

            .nav-pills li.active > a
            {
                background-color:#5e2d79!important;
                color:#fff9f0!important;
                box-shadow: none!important;
                font-weight:normal!important;
            }

            .nav-pills li:not(.active) a:hover {
                color:transparent!important;
                background-color:#5e2d79!important;
                border-top:1px solid #fff;
            }

            .bg-img, .guest {
                background:url('<?= $this->getAsset('rosey/images/pink-rose-50_1.jpg') ?>');
                /*background-size: 100% 100%;*/
            }

            article {
                min-height:300px!important;
            }

            a.btn-navbar {
                margin-top:10px;
                float:left!important;
            }

            .navbar-fixed-bottom {
                background-color:#5e2d79;
                padding-bottom:10px;
                color:#fff;
            }

            .navbar-fixed-bottom hr {
                margin-top:0px;
                margin-bottom:10px;
            }

            .navbar-fixed-bottom a {
                color:#fff;
            }

            @media (max-width:979px) {
                body {
                    margin-bottom:50px;
                }
                .navbar {
                    min-height:100px;
                    height:auto;
                    max-height: 150px;
                }

                header h1 {
                    /*margin:0px;*/
                }

                .nav-pills {
                    margin-left:0!important;                    
                }

                .nav-collapse {
                    background:url('<?= $this->getAsset('rosey/images/custom-2.png') ?>');
                }
                .nav-collapse.in {
                    border:1px solid #5e2d79;
                    border-radius: 5px;
                }
            }
        </style>
        <link href="<?= $this->getAsset('rosey/css/bootstrap-responsive.min.css') ?>" rel="stylesheet">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!-- Fav and touch icons -->
        <link rel="shortcut icon" href="<?= $this->getAsset('images/logo') ?>">
    </head>

    <body>
        <header class="navbar">
            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="span10 offset1" style="position:relative;">
                        <a href="<?= $this->home() ?>"><img class="img-circle img-polaroid" src="<?= CMS::getLogoPath() ?>" align="left" />
                            <h1>
                                <?= CMS::getSiteName() ?>
                            </h1>
                        </a>
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <nav class="nav-collapse collapse">
                            <ul class="nav nav-pills">
                                <?= CMS::createPageLinks('nav-pills') ?>
                            </ul>
                            <ul class="nav nav-pills pull-right">
                                <?php if ($this->userIdentity()->isGuest()): ?>
                                    <li><a href="<?= $this->url('cms', 'guest', 'login') ?>">Login</a></li>
                                <?php endif; ?>
                                <?php if (!$this->userIdentity()->isGuest()): ?>
                                    <li><a href="<?= $this->url('cms', 'dashboard', $this->userIdentity()->getUser()->getRole()) ?>">Dashboard</a></li>
                                    <li><a href="<?= $this->url('cms', 'guest', 'logout') ?>">Logout</a></li>
                                <?php endif; ?>
                            </ul>
                        </nav>
                    </div>  
                </div>
            </div>               
        </header>
        <section class="container-fluid">
            <?php if ($this->flash()->hasMessage()): ?>
                <div class="row-fluid">
                    <div class="span12 alert alert-info" style="text-align:center">
                        <?= $this->flash()->getMessage() ?>
                    </div>
                </div>
            <?php endif; ?>
            <?php if ($this->flash()->hasSuccessMessage()): ?>
                <div class="row-fluid">
                    <div class="span12 alert alert-success" style="text-align:center">
                        <?= $this->flash()->getSuccessMessage() ?>
                    </div>
                </div>
            <?php endif; ?>
            <?php if ($this->flash()->hasErrorMessage()): ?>
                <div class="row-fluid">
                    <div class="span12 alert alert-error" style="text-align:center">
                        <?= $this->flash()->getErrorMessage() ?>
                    </div>
                </div>
            <?php endif; ?>
            <?= $content ?>
        </section> <!-- /container -->
        <div class="navbar-fixed-bottom">
            <hr/>
            <div class="container-fluid">
                <footer class="footer">
                    &copy; 2014 <a target="_blank" href="http://dscribe.ezraobiwale.com/modules/cms">DScribe Framework CMS</a>
                </footer>
            </div>
        </div>
        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="<?= $this->getAsset('rosey/js/bootstrap.min.js') ?>"></script>
        <script>
            function closeAlert() {
                $('.alert').not('.no-close').fadeOut();
            }
            $(document).ready(function() {
                setTimeout(closeAlert, 5000);
            });
        </script>
    </body>
</html>
