<?php ob_start() ?>
<div class="row-fluid">
    <div class="span7 offset1 well bg-img">
        <div class="row-fluid">
            <div class="span12">
                <h1>
                    <small class="text-error"><?= CMS::getArticle()->getTitle() ?></small>
                    <small class="pull-right" style="color:#999;font-size:12px">
                        category: <a href="<?= CMS::getArticleCategoryLink() ?>"><?= CMS::getArticle()->getCategory() ?></a><br />
                        <?= \DBScribe\Util::createTimestamp(CMS::getArticle()->getDateModified(), 'jS M, Y') ?>
                    </small>
                </h1>
            </div>
        </div>
        <hr />
        <div class="row-fluid">
            <div class="span12">
                <?= CMS::getArticle()->getContent() ?>
            </div>
        </div>
        <hr />
        <div class="row-fluid">
            <div class="span12">
                <?= CMS::getCommentForm(true) ?>
            </div>
        </div>
    </div>
    <aside class="span3">
        <div class="row-fluid">
            <div class="span12 well well-small text-info bg-img">
                Subscribe here
                <?= CMS::createSubscriptionForm() ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12 well well-small bg-img">
                <h3><small class="text-error">Other Articles in Category</small></h3>
                <?= CMS::createArticleLinks(5, array('class' => 'nav nav-tabs nav-stacked well well-small')) ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12 well well-small bg-img">
                <h3><small class="text-error">Other Categories <a class="btn-link text-warning" style="font-style:italic" href="<?= $this->url('cms', 'article', 'list-categories') ?>">(view all)</a></small></h3>
                <?= CMS::createArticleCategoryLinks(5, array('class' => 'nav nav-tabs nav-stacked well well-small')) ?>
            </div>
        </div>
    </aside>
</div>
<?php
$this->loadLayout('rosey/cms-main', array(
    'content' => ob_get_clean(),
));
