<div class="row-fluid">
    <div class="span10 offset1 guest">
        <div class="row-fluid">
            <div class="span8 offset2 page-header">
                <h1 class="text-error">
                    <?= $title ?>
                </h1>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span8 offset2">
                <?= TwbForm::horizontal($form) ?>
            </div>
        </div>        
    </div>
</div>