<?php
Table::init(array('class' => 'table table-bordered table-hover table-condensed data'));

$count = 1;
foreach ($groupedArticles as $category => $articles) {
    Table::newRow(array('id' => $category, 'class' => 'active alert-info'));
    Table::addRowData($count);
    $title = '<span class="category name">' . $category . '</span>';
    Table::addRowData($title, array('colspan' => 3));
    $count++;

    foreach ($articles as $key => $article) {
        if (in_array($article->getId(), $used['pages']))
            continue;

        $used['pages'][] = $article->getId();
        $editBtn = '<a href="' . $this->url('cms', 'article', 'edit', array($article->getId())) . '" class="btn btn-link text-info"><i class="icon-edit"></i> edit</a>';
        $deleteBtn = TwBootstrap::customModal(array(
                    'href' => $this->url('cms', 'article', 'delete', array($article->getId())),
                    'linkLabel' => '<i class="icon-trash"></i> delete',
                    'linkAttrs' => array(
                        'class' => 'btn btn-link text-error'
                    )
        ));
        $commentsBtn = TwBootstrap::customModal(array(
                    'href' => $this->url('cms', 'article', 'comments', array($article->getId())),
                    'linkLabel' => '<i class="icon-comment"></i> comments',
                    'linkAttrs' => array(
                        'class' => 'btn btn-link text-success'
                    )
        ));
        $copyBtn = '<a href="' . $this->url('cms', 'article', 'copy-article', array($article->getId())) . '" class="btn btn-link text-warning"><i class="icon-share"></i> copy</a>';

        Table::newRow(array('id' => $article->getId(), 'class' => $article->getStatus() ? 'active alert-success page-row' : 'inactive alert-error article-row', 'title' => $article->getStatus() ? 'Active Article' : 'Inactive Article'));

        $title = '<a class="article name" title="view article" href="' . $this->url('cms', 'article', 'view', array($article->getLink())) . '" class="btn btn-link btn-success">' . $article->getTitle() . '</a>';
        $title .= '<br /><small class="info">' . $article->getLink() . '</small>';
        Table::addRowData('::::', array('width' => '5px'));
        Table::addRowData($key + 1, array('width' => '5px'));
        Table::addRowData($title);
        Table::addRowData($commentsBtn . $copyBtn . $editBtn . $deleteBtn, array('width' => '230px', 'class' => 'actions'));
    }
}
?>
<style>
    td.actions {
        vertical-align: middle!important;
        text-align:center!important;
    }
    .article {

    }
    .info {
        font-style:italic;
        font-size:small;
    }

    .category {

    }

    .parent {

    }

    tr:hover .article {
        font-weight:bolder;
    }
</style>
<div class="row-fluid">
    <div class="span12">
        <h1>
            <small class="text-error">Articles <input type="search" class="search-query" placeholder="case-sensitive search..." style="min-width:0!important;min-height:0!important;" /></small>
            <!--<a id="statics" href="<?= $this->url('cms', 'article', 'statics') ?>" class="btn btn-info pull-right">Create/Update Static Articles</a>-->
            <a href="<?= $this->url('cms', 'article', 'new') ?>" style="margin-right:5px" class="btn btn-success pull-right">New Article</a>
        </h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <?= Table::render() ?>
    </div>
</div>
<script>
    $(function() {
        $('input[type="search"]').live('keyup', function() {
            var self = this;
            $('table.data .name').each(function(i, v) {
                if ($(v).html().indexOf($(self).val()) == -1) {
                    $(v).parents('tr').addClass('hidden');
                }
                else {
                    $(v).parents('tr').removeClass('hidden');
                }
            });
        });
        $('#statics').live('click', function(e) {
            e.preventDefault();
            $(this).html('working ...').addClass('disabled');
            var self = this;
            $.get('/cms/article/statics', {}, function(data) {
                $(self).html('Static Articles Created');
                alert(data);
            });
        });
    });
</script>
