<?php ob_start(); ?>
<?=
TwBootstrap::customModal(array(
    'href' => '/cms/category/form-list/' . $categoryId,
    'linkLabel' => 'Select Category',
    'linkAttrs' => array(
        'class' => 'btn btn-success btn-category btn-mini hidden',
        'style' => 'margin-left:10px'
    ),
    'modalId' => 'cms-page-modal',
    'header' => '
    <h1 class="text-success clear">
        <small>Page Categories</small>
        <a href="/cms/category/new" class="btn btn-success btn-mini" style="float:none">New Category</a>
    </h1>'
        ), true);
?>
<style>
    input:not([type="submit"]):not([type="button"]):not([type="checkbox"]):not([type="radio"]), textarea, select {
        min-width:10px!important;
    }
    #pageForm .info {
        background-color:#dff0d8;
        padding:5px;
        border-radius:10px;
        border:1px solid #468847;
        margin-bottom:20px;
    }

    #pageForm .info label {
        color:#468847;
    }

    .inline-1 label {
        display:inline;
    }

    .inline-1 .element-group:first-child {
        padding-right:50px;
    }

    @media (max-width: 767px) {
        #pageForm .info {
            margin-top:20px; 
        }
    }
</style>
<div class="row-fluid header">
    <div class="span12">
        <h1><small class="text-error"><?= $type ?> Page</small></h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <?= $form->setAttribute('action', $this->currentPath())->render() ?>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('form#pageForm').addClass('hidden');
        if ('<?= $type ?>' == 'New')
            $('form#pageForm input[type="submit"]').parent().append('<input class="btn btn-primary" type="submit" name="saveAndNew" value="Save and Add New" />');

        $('form#pageForm').prepend('<div class="info container-fluid"><div class="details"></div></div>');
        $('form#pageForm #title, form#pageForm #link, form#pageForm #description').parents('.element-group').each(function(index, value) {
            $(value).addClass('clear');
            $('form#pageForm .info > .details').prepend($(value));
        });

        var details = $('form#pageForm .info > .details');
        $(details).prepend('<div class="row-fluid inline-1"></div>');
        $('form#pageForm .inline-1').prepend($('form#pageForm #status').parents('.element-group').addClass('pull-left'));
        $('form#pageForm .inline-1').prepend($('form#pageForm #category').parents('.element-group').addClass('pull-left'));

        $(details).append('<div class="row-fluid inline-2"></div>');
        $('form#pageForm .inline-2').prepend($('form#pageForm #allowComments').parents('.element-group').addClass('span5'));
        $('form#pageForm .inline-2').prepend($('form#pageForm #isHomePage').parents('.element-group').addClass('span3'));
        $('form#pageForm .inline-2').prepend($('form#pageForm #position').parents('.element-group').addClass('span3'));
        $(details).append($('form#pageForm #submit').parents('.element-group'));

        $('form#pageForm .element-group.submit').addClass('pull-right');
        $('form#pageForm select').addClass('span12');

        $('form#pageForm .info').prepend($('.row-fluid.header'));
        $('.row-fluid.header h1').append('<a href="#" class="show-info" title="Minimize"><i class="icon-minus-sign"></i></a>');

        $('form#pageForm a.show-info').live('click', function(e) {
            e.preventDefault();
            if ($(details).css('display') == 'none') {
                $(details).slideDown();
                $(this).children('i').addClass('icon-minus-sign').removeClass('icon-plus-sign');
                $(this).attr('title', 'Minimize');
                $('form#pageForm #title').focus();
            }
            else {
                $(details).slideUp();
                $(this).children('i').removeClass('icon-minus-sign').addClass('icon-plus-sign');
                $(this).attr('title', 'Maximize');
            }
        });

        if ($('h1 .text-error').html().indexOf('Edit') != -1)
            $('form#pageForm a.show-info').click();

        var cat = $('form#pageForm select#category').hide().parent();
        $(cat).append('<span class="badge badge-info" id="currentCategory">' + $('form#pageForm select#category > option[value="' +
                $('form#pageForm select#category').val() + '"]').html() + '</span>')
                .append($('.btn-category')
                        .removeClass('hidden')
                        .attr('href', $('.btn-category').attr('href') + '/' +
                                $('form#pageForm select#category').children().val() +
                                '/' + $('form#pageForm select#category').val()));
        $('#newCategory').remove();

        // get the selected value from category list
        $('.categoryValue').live('click', function(e) {
            e.preventDefault();
            $('form#pageForm select#category').val($(this).attr('data-value'));

            $('#currentCategory').html($(this).html());

            $('form#pageForm a.btn-category').attr('href', '/cms/category/form-list/' + $(this).attr('data-value'));
        });

        var stat = $('form#pageForm #status').hide().parent();
        $(stat).append('<a href="#" data-type="select" data-target="form#pageForm #status" data-on="Active" data-off="Inactive" class="btn btn-mini toggle btn-' + (($('form#pageForm #status').val() == 1) ? 'success active' : 'danger') + '" data-toggle="button">' + (($('form#pageForm #status').val() == 1) ? 'Active' : 'Inactive') + '</button>');

        var stat = $('form#pageForm #isHomePage').hide().parent();
        $(stat).append('<a href="#" data-target="form#pageForm #isHomePage" data-on="Yes" data-off="No" class="btn btn-mini toggle btn-' + (($('form#pageForm #isHomePage').attr('checked')) ? 'success active' : 'danger') + '" data-toggle="button">' + (($('form#pageForm #isHomePage').attr('checked')) ? 'Yes' : 'No') + '</button>');

        var stat = $('form#pageForm #allowComments').hide().parent();
        $(stat).append('<a href="#" data-target="form#pageForm #allowComments" data-on="Yes" data-off="No" class="btn btn-mini toggle btn-' + (($('form#pageForm #allowComments').attr('checked')) ? 'success active' : 'danger') + '" data-toggle="button">' + (($('form#pageForm #allowComments').attr('checked')) ? 'Yes' : 'No') + '</button>');
        $('form#pageForm').removeClass('hidden');

        $('.toggle').live('click', function(e) {
            e.preventDefault();

            if ($(this).hasClass('active')) {
                $(this).html($(this).attr('data-on')).removeClass('btn-danger').addClass('btn-success active');
                $($(this).attr('data-target')).attr('checked', 'checked');
            }
            else {
                $(this).html($(this).attr('data-off')).removeClass('btn-success active').addClass('btn-danger');
                $($(this).attr('data-target')).removeAttr('checked');
            }

            if ($(this).attr('data-type') === 'select') {
                self = this;
                $($(this).attr('data-target')).children('option').each(function(i, v) {
                    if ($(v).html() === $(self).html())
                        $(v).attr('selected', 'selected');
                    else
                        $(v).removeAttr('selected');
                });
            }
        });
    });
</script>
<?php
$this->loadLayout('tinymce', array(
    'content' => ob_get_clean()
));
