<?php
Table::init(array('class' => 'table table-bordered table-hover table-condensed data'));

$used['categories'] = $used['pages'] = array();

$count = 1;
foreach ($categories as $ky => $category) {
    $pages = $category->page(array(
        'orderBy' => array('position', 'title'),
    ));

    if (in_array($category->getId(), $used['categories']))
        continue;
    if ($category->getParent()) {
        $used['categories'][] = $category->getId();
        $editBtn = '<a href="' . $this->url('cms', 'category', 'edit', array($category->getId())) . '" class="btn btn-link text-info"><i class="icon-edit"></i> edit</a>';
        $deleteBtn = TwBootstrap::customModal(array(
                    'href' => $this->url('cms', 'category', 'delete', array($category->getId())),
                    'linkLabel' => '<i class="icon-trash"></i> delete',
                    'linkAttrs' => array(
                        'class' => 'btn btn-link text-error'
                    )
        ));
        Table::newRow(array('id' => $category->getId(), 'class' => $category->getStatus() ? 'active alert-info' : 'inactive alert no-close', 'title' => $category->getStatus() ? 'Active Category' : 'Inactive Category'));
        Table::addRowData($count);
        $title = '<span class="category name">' . $category->getName() . '</span> <span class="info">' . $category->getLink() . '</span>';
        $parent = $category->category()->first();
        if ($parent)
            $title .= ' (<a class="parent" title="see parent category (' . $parent->getName() . ')" href="#' . $parent->getId() . '">parent category</a>)';
        Table::addRowData($title, array('colspan' => 2));
        Table::addRowData($editBtn . $deleteBtn, array('class' => 'actions'));
        $count++;
    }

    foreach ($pages as $key => $page) {
        if (in_array($page->getId(), $used['pages']))
            continue;

        $used['pages'][] = $page->getId();
        $editBtn = '<a href="' . $this->url('cms', 'page', 'edit', array($page->getId())) . '" class="btn btn-link text-info"><i class="icon-edit"></i> edit</a>';
        $deleteBtn = TwBootstrap::customModal(array(
                    'href' => $this->url('cms', 'page', 'delete', array($page->getId())),
                    'linkLabel' => '<i class="icon-trash"></i> delete',
                    'linkAttrs' => array(
                        'class' => 'btn btn-link text-error'
                    )
        ));
        $commentsBtn = TwBootstrap::customModal(array(
                    'href' => $this->url('cms', 'page', 'comments', array($page->getId())),
                    'linkLabel' => '<i class="icon-comment"></i> comments',
                    'linkAttrs' => array(
                        'class' => 'btn btn-link text-success'
                    )
        ));
        $copyBtn = '<a href="' . $this->url('cms', 'page', 'copy-page', array($page->getId())) . '" class="btn btn-link text-warning"><i class="icon-share"></i> copy</a>';

        Table::newRow(array('id' => $page->getId(), 'class' => $page->getStatus() ? 'active alert-success page-row' : 'inactive alert-error page-row', 'title' => $page->getStatus() ? 'Active Page' : 'Inactive Page'));

        $title = '<a class="page name" title="view page" href="' . $this->url('cms', 'page', 'view', array($category->getLink(), $page->getLink())) . '" class="btn btn-link btn-success">' . $page->getTitle() . '</a>';
        $title .= '<br /><small class="info">' . $page->getLink();
        if ($page->getIsHomePage())
            $title .= ' | homepage';
        $title .= '</small>';
        Table::addRowData('::::', array('width' => '5px'));
        Table::addRowData($key + 1, array('width' => '5px'));
        Table::addRowData($title);
        Table::addRowData($commentsBtn . $copyBtn . $editBtn . $deleteBtn, array('width' => '230px', 'class' => 'actions'));
    }
}
?>
<style>
    td.actions {
        vertical-align: middle!important;
        text-align:center!important;
    }
    .page {

    }
    .info {
        font-style:italic;
        font-size:small;
    }

    .category {

    }

    .parent {

    }

    tr:hover .page {
        font-weight:bolder;
    }
</style>
<div class="row-fluid">
    <div class="span12">
        <h1>
            <small class="text-error">Pages <input type="search" class="search-query" placeholder="case-sensitive search..." style="min-width:0!important;min-height:0!important;" /></small>
            <!--<a id="statics" href="<?= $this->url('cms', 'page', 'statics') ?>" class="btn btn-info pull-right">Create/Update Static Pages</a>-->
            <a href="<?= $this->url('cms', 'page', 'new') ?>" style="margin-right:5px" class="btn btn-success pull-right">New Page</a>
        </h1>
        <hr />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <?= Table::render() ?>
    </div>
</div>
<script>
    $(function() {
        $('input[type="search"]').live('keyup', function() {
            var self = this;
            $('table.data .name').each(function(i, v) {
                if ($(v).html().indexOf($(self).val()) == -1) {
                    $(v).parents('tr').addClass('hidden');
                }
                else {
                    $(v).parents('tr').removeClass('hidden');
                }
            });
//            $('table.data > tbody > tr').each(function(i, v) {
//                if ($(v).children().children('.name').html().indexOf($(self).val()) == -1) {
//                    $(v).addClass('hidden');
//                }
//                else {
//                    $(v).removeClass('hidden');
//                }
//            });
        });
        $('#statics').live('click', function(e) {
            e.preventDefault();
            $(this).html('working ...').addClass('disabled');
            var self = this;
            $.get('/cms/page/statics', {}, function(data) {
                $(self).html('Static Pages Created');
                alert(data);
            });
        });
    });
</script>
